# -*- coding: utf-8 -*-
"""cleandataset_headphones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MuELJFz0hYyxMmyUrMIgvPImU8FkPu-J
"""

import numpy as np
import pandas as pd
import seaborn as sns
import os

#print(os.listdir(()))
df = pd.read_csv("Merged_reviews_cleaned.csv" )

df

#drop the columns named "rating", "is_verified", "helpful_count"
df = df.drop(["rating", "is_verified", "helpful_count"], axis=1)

df.columns

df

# Split the 'title' column into 'rating' and 'review' with the relevant information
df[['Rating', 'review']] = df['title'].str.split(' stars', n=1, expand=True)
df['Rating'] = df['Rating'].str.strip()
df['review'] = df['review'].str.strip()

df

df = df.drop('title', axis=1)

df.columns

df

df = df.drop(["Rating", "Description"], axis=1)

df

# split the product_attributes column into separate columns
df[['product_color', 'product_model']] = df['product_attributes'].str.split('Set:', expand=True)

# drop the original product_attributes column
df = df.drop('product_attributes', axis=1)

# remove the "Color: " prefix from the product_color column
df['product_color'] = df['product_color'].str.replace('Color: ', '')

df

df.dtypes

#checking for null values
df.isnull().sum()

# missing_value=[ "N/a", "na" , np.nan]
# df = pd.read_csv("Merged_reviews_cleaned.csv", na_values = missing_value)

# Forward fill null values with the values from above cells
df['product_color'].fillna(method='ffill', inplace=True)
df['product_model'].fillna(method='ffill', inplace=True)

df.isnull().sum()

#print rows with null values
df[df.isnull().any(axis=1)]

#drop rows that have null values
df = df.dropna()

df.isnull().sum()
#all null values cleared

# removeing certain parts of the prduct color column
df_copy = df.copy()
df_copy['product_color'] = df_copy['product_color'].str.replace('Size: One SizeStyle: Headphones', '')
df_copy['product_color'] = df_copy['product_color'].str.replace('Sizeadphones', '')
df_copy['product_color'] = df_copy['product_color'].str.replace('Style: OriginalPattern: Headphones', '')
df_copy['product_color'] = df_copy['product_color'].str.replace('Style: Special EditionPattern: Headphones', '')

df = df_copy

#dropping the product model, becuase the name is not metioned for all products. In accurate information in this column can lead to wrong conclusions
df = df.drop('product_model', axis=1)

df.to_csv("cleaned.csv", index=False)