# -*- coding: utf-8 -*-
"""Copy of JSON reviews to dataframe

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yOc-Pvb62sgCAzBV9iO8fvOXR106Iiun
"""

import json
import pandas as pd

file_path = '/content/Soundcore.json'
with open(file_path, 'r') as file:
    data = json.load(file)

reviews_data = []
count = 0
for result in data['results']:
  asin = result['content']["asin"]
  for review in result['content']['reviews']:
    count += 1
    try:
      review_info = {
      'review_id': review['id'],
      'product_id': asin,
      "title": review["title"],
      "author": review["author"],
      "rating": review["author"],
      "content": review["content"],
      "timestamp": review["timestamp"],
      "profile_id": review["profile_id"],
      "is_verified": review["is_verified"],
      "helpful_count": review.get('helpful_count', 0),
      "product_attributes": review["product_attributes"]
      }
      reviews_data.append(review_info)
    except:
      print(count)
      break

reviews_df = pd.DataFrame(reviews_data)
reviews_df.to_csv('reviews_11.csv', index=False)
reviews_df

df_1 = pd.read_csv('/content/reviews_1.csv')
df_2 = pd.read_csv('/content/reviews_2.csv')
df_3 = pd.read_csv('/content/reviews_3.csv')
df_4 = pd.read_csv('/content/reviews_4.csv')
df_5 = pd.read_csv('/content/reviews_5.csv')
df_6 = pd.read_csv('/content/reviews_6.csv')
df_7 = pd.read_csv('/content/reviews_7.csv')
df_8 = pd.read_csv('/content/reviews_8.csv')
df_9 = pd.read_csv('/content/reviews_9.csv')
df_10 = pd.read_csv('/content/reviews_10.csv')

df_2.head()

merged_df = pd.concat([df_1, df_2, df_3, df_4, df_5, df_6, df_7, df_8, df_9,df_10], ignore_index=True)
merged_df

merged_df.to_csv('merged_reviews.csv', index=False)